name = "kuma"
main = "src/index.ts"
compatibility_date = "2024-12-24"
minify = true
upload_source_maps = true
workers_dev = false
preview_urls = false

[assets]
directory = "./dist/"

[[routes]]
pattern = "kuma.chaimi.cc/*"
zone_name = "chaimi.cc"

[build]
command = "bun run build"
