compatibility_date = "2024-12-05"
main = "src/index.ts"
minify = true
name = "kuma"
upload_source_maps = true
workers_dev = false
preview_urls = false

[assets]
directory = "./dist/"

[[routes]]
pattern = "kuma.chaimi.cc/*"
zone_name = "chaimi.cc"

[build]
command = "pnpm build"
